// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAg2zpnZRN74HEmZgZZ1f8NW8OXXaLZTv4',
    appId: '1:633391327654:web:2c8cfc06deec4069b88767',
    messagingSenderId: '633391327654',
    projectId: 'healthcare-578bf',
    authDomain: 'healthcare-578bf.firebaseapp.com',
    databaseURL: 'https://healthcare-578bf-default-rtdb.firebaseio.com',
    storageBucket: 'healthcare-578bf.firebasestorage.app',
    measurementId: 'G-5310J046NY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6yKs14UIb90kIeucZ9iepPgZD1_8XQ5c',
    appId: '1:633391327654:android:1279c25404aaa8b3b88767',
    messagingSenderId: '633391327654',
    projectId: 'healthcare-578bf',
    databaseURL: 'https://healthcare-578bf-default-rtdb.firebaseio.com',
    storageBucket: 'healthcare-578bf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNOveg9171do3Ueqqlw_jT5TxB4WD6USE',
    appId: '1:633391327654:ios:78934f16a34f934cb88767',
    messagingSenderId: '633391327654',
    projectId: 'healthcare-578bf',
    databaseURL: 'https://healthcare-578bf-default-rtdb.firebaseio.com',
    storageBucket: 'healthcare-578bf.firebasestorage.app',
    iosBundleId: 'com.example.healthcare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNOveg9171do3Ueqqlw_jT5TxB4WD6USE',
    appId: '1:633391327654:ios:78934f16a34f934cb88767',
    messagingSenderId: '633391327654',
    projectId: 'healthcare-578bf',
    databaseURL: 'https://healthcare-578bf-default-rtdb.firebaseio.com',
    storageBucket: 'healthcare-578bf.firebasestorage.app',
    iosBundleId: 'com.example.healthcare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAg2zpnZRN74HEmZgZZ1f8NW8OXXaLZTv4',
    appId: '1:633391327654:web:71674f9efb3fb597b88767',
    messagingSenderId: '633391327654',
    projectId: 'healthcare-578bf',
    authDomain: 'healthcare-578bf.firebaseapp.com',
    databaseURL: 'https://healthcare-578bf-default-rtdb.firebaseio.com',
    storageBucket: 'healthcare-578bf.firebasestorage.app',
    measurementId: 'G-XEXKBF2JTP',
  );

}